# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rohit Singh
email: lb.rohitsingh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Rohit is a Information Technology Btech student at KIET group of institution Ghaziyabad.
  He works at a Health Care providing Comapany - ApniCare. His interests focus on Providing better Health Care to all people.
  He actively maintains th Server of Project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "#" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rohit_lb
github_username:  rohitlb


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
